export const provinceOptions = [
    { key: '1', value: 'af', text: 'Buenos Aires' },
    { key: '2', value: 'ax', text: 'Capital Federal' },
    { key: '3', value: 'al', text: 'Catamarca' },
    { key: '4', value: 'dz', text: 'Chaco' },
    { key: '5', value: 'as', text: 'Chubut' },
    { key: '6', value: 'ad', text: 'Córdoba' },
    { key: '7', value: 'ao', text: 'Corrientes' },
    { key: '8', value: 'ai', text: 'Entre Ríos' },
    { key: '9', value: 'ag', text: 'Formosa' },
    { key: '10', value: 'ar', text: 'Jujuy' },
    { key: '11', value: 'am', text: 'La Pampa' },
    { key: '12', value: 'aw', text: 'La Rioja' },
    { key: '13', value: 'au', text: 'Mendoza' },
    { key: '14', value: 'at', text: 'Misiones' },
    { key: '15', value: 'az', text: 'Neuquén' },
    { key: '16', value: 'bs', text: 'Río Negro' },
    { key: '17', value: 'bh', text: 'Salta' },
    { key: '18', value: 'bd', text: 'San Juan' },
    { key: '19', value: 'bb', text: 'San Luis' },
    { key: '20', value: 'by', text: 'Santa Cruz' },
    { key: '21', value: 'be', text: 'Santa Fe' },
    { key: '22', value: 'bz', text: 'Santiago del Estero' },
    { key: '23', value: 'bj', text: 'Tierra del Fuego' },
    { key: '24', value: 'bj', text: 'Tucumán' },
]