export const provinceOptions = [
    { key: '1', value: 'Buenos Aires', text: 'Buenos Aires' },
    { key: '2', value: 'Capital Federal', text: 'Capital Federal' },
    { key: '3', value: 'Catamarca', text: 'Catamarca' },
    { key: '4', value: 'Chaco', text: 'Chaco' },
    { key: '5', value: 'Chubut', text: 'Chubut' },
    { key: '6', value: 'Córdoba', text: 'Córdoba' },
    { key: '7', value: 'Corrientes', text: 'Corrientes' },
    { key: '8', value: 'Entre Ríos', text: 'Entre Ríos' },
    { key: '9', value: 'Formosa', text: 'Formosa' },
    { key: '10', value: 'Jujuy', text: 'Jujuy' },
    { key: '11', value: 'La Pampa', text: 'La Pampa' },
    { key: '12', value: 'La Rioja', text: 'La Rioja' },
    { key: '13', value: 'Mendoza', text: 'Mendoza' },
    { key: '14', value: 'Mendoza', text: 'Misiones' },
    { key: '15', value: 15, text: 'Neuquén' },
    { key: '16', value: 'Río Negro', text: 'Río Negro' },
    { key: '17', value: 'Salta', text: 'Salta' },
    { key: '18', value: 'San Juan', text: 'San Juan' },
    { key: '19', value: 'San Luis', text: 'San Luis' },
    { key: '20', value: 'Santa Cruz', text: 'Santa Cruz' },
    { key: '21', value: 'Santa Fe', text: 'Santa Fe' },
    { key: '22', value: 'Santiago del Estero', text: 'Santiago del Estero' },
    { key: '23', value: 'Tierra del Fuego', text: 'Tierra del Fuego' },
    { key: '24', value: 'Tucumán', text: 'Tucumán' },
]